### ISSUE TITLE
和Mohist不兼容，世界生成问题

### ISSUE THREAD

**Issue by ElainAwa** [Scarasol/Sona-Survival-101#1]
server：mohist-1.20.1-871-server
mod：sona-1.20.1-forge-1.0.2
无法正常生成世界
今天凌晨2点mohist修复了一下，可以启动服务器了，现在应该是模组本身的兼容性问题
[latest.log](https://github.com/user-attachments/files/17239756/latest.log)
![869C0666485BE03B3DDE42F1F0C0D6F3](https://github.com/user-attachments/assets/7799cd1f-ef7d-430f-9d20-edb155525347)

**Comment by Scarasol** [comment]
墨佬已经修复了
